server:
  port: 9090
dubbo:
  provider:
    retries: 1
    timeout: 10000
  protocols:
    dubbo:
      name: dubbo
      port: -1
  reference:
    check: false
  cloud:
    subscribed-services: service-user
system:
# 是否开启拦截
  rest:
    interceptor: false
# Oauth2
  secret:
    jwt: acgist
    web: acgist
    rest: acgist
  validity:
    code: 600
    access: 7200
    refresh: 25200
  jwt: jwt.jks
