server:
  port: 9090
dubbo:
  provider:
    retries: 1
    timeout: 10000
  protocols:
    dubbo:
      name: dubbo
      port: -1
  reference:
    check: false
  cloud:
    subscribed-services: service-pay, service-user
system:
  rest:
    interceptor: false # 是否开启拦截
  secret: acgist