dubbo:
# 等于：@DubboComponentScan
  scan:
    base-packages: com.acgist.pay
  provider:
    retries: 1
    timeout: 10000
  protocols:
    dubbo:
      name: dubbo
      port: -1
  reference:
    check: false
  cloud:
    subscribed-services:
#  可以不用配置
#  registry.address: spring-cloud://localhost
