server:
  port: 8888
dubbo:
  cloud:
    subscribed-services: service-user
spring:
  cloud:
    gateway:
      routes:
       - id: rest-api
         uri: lb://rest-api
         predicates:
           - Path=/rest/api/**
         filters:
           - StripPrefix=1
           - name: Retry
             args:
               retries: 1
       - id: rest-api-yusheng
         uri: lb://rest-api-yusheng
         predicates:
           - Path=/rest/yusheng/api/**
         filters:
           - StripPrefix=1
           - name: Retry
             args:
               retries: 1
       - id: rest-open
         uri: lb://rest-open
         predicates:
           - Path=/rest/open/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: rest-oauth
         uri: lb://rest-oauth
         predicates:
           - Path=/oauth/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: web
         uri: lb://web
         predicates:
           - Path=/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: web-resources
         uri: lb://web-resources
         predicates:
           - Path=/resources/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: prometheus
         uri: http://localhost:9090
         predicates:
           - Host=prometheus.acgist.com
       - id: grafana
         uri: http://localhost:3000
         predicates:
           - Host=grafana.acgist.com
       - id: nacos
         uri: http://localhost:8848
         predicates:
           - Host=nacos.acgist.com
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth/token_key
