server:
  port: 8888
# 如果需要监控
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
spring:
  cloud:
    gateway:
      routes:
       - id: rest-api
         uri: lb://rest-api
         predicates:
           - Path=/rest/api/**
         filters:
           - StripPrefix=1
           - name: Retry
             args:
               retries: 1
       - id: rest-api-yusheng
         uri: lb://rest-api-yusheng
         predicates:
           - Path=/rest/yusheng/api/**
         filters:
           - StripPrefix=1
           - name: Retry
             args:
               retries: 1
       - id: rest-oauth
         uri: lb://rest-oauth
         predicates:
           - Path=/oauth/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: web-user
         uri: lb://web-user
         predicates:
           - Path=/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: web-resources
         uri: lb://web-resources
         predicates:
           - Path=/resources/**
         filters:
           - name: Retry
             args:
               retries: 1
       - id: prometheus
         uri: http://localhost:9090
         predicates:
           - Host=prometheus.acgist.com
       - id: grafana
         uri: http://localhost:3000
         predicates:
           - Host=grafana.acgist.com
       - id: nacos
         uri: http://localhost:8848
         predicates:
           - Host=nacos.acgist.com
