spring:
  freemarker:
    cache: false
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings: 
      classic_compatible: true
